apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: backend
  name: backend
  namespace: sync
spec:
  containers:
  - image: shigeshino/backend:0.1.RELEASE
    name: backend
    resources: {}
    containerPorts:
    - port: 8080
      #  imagePullSecrets:
      # - name: regcred
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
