apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: backend
  name: backend-svc
  namespace: sync
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30282
  selector:
    run: backend
  type: NodePort
status:
  loadBalancer: {}
